import{motion}from'framer-motion';import{Link,useParams}from'react-router-dom';import{useQuery}from'@tanstack/react-query';import{catalog,wallet,orders,admin}from'../api/client';import Card from'../components/Card';
export function Home(){return <main className="wrap"><motion.section initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="py-20"><h1 className="text-6xl font-black">Premium gift cards, delivered instantly.</h1><p className="muted text-xl">Buy global digital vouchers with secure wallet funding and Reloadly fulfillment.</p><Link className="btn inline-block mt-6" to="/store">Shop trending cards</Link></motion.section><div className="gridcards">{['Trending Gift Cards','Top Brands','Countries','Features','Testimonials','FAQ','Newsletter'].map(x=><Card key={x} title={x}><p className="muted">Curated live marketplace content powered by connected APIs and CMS settings.</p></Card>)}</div></main>}
export function Store(){const{data}=useQuery({queryKey:['products'],queryFn:()=>catalog.products().then(r=>r.data)});return <main className="wrap"><h1>Store</h1><div className="gridcards">{(data?.products||[]).map(p=><Link to={`/product/${p.id}`} className="glass card" key={p.id}><h2>{p.name}</h2><p className="muted">{p.country_code} · {p.currency}</p><b>${p.price}</b></Link>)}</div></main>}
export function Product(){const{id}=useParams();const{data}=useQuery({queryKey:['product',id],queryFn:()=>catalog.product(id).then(r=>r.data)});return <main className="wrap"><Card title={data?.product?.name||'Gift Card'}><p>{data?.product?.description}</p><button className="btn">Buy with wallet</button></Card></main>}
export function Dashboard(){const{data}=useQuery({queryKey:['wallet'],queryFn:()=>wallet.summary().then(r=>r.data)});return <main className="wrap"><h1>Dashboard</h1><div className="gridcards"><Card title="Wallet"><b>${data?.wallet?.balance||'0.00'}</b></Card><Card title="Orders"><Link to="/orders">View orders</Link></Card><Card title="Notifications"><p className="muted">Unread alerts and purchase updates.</p></Card></div></main>}
export function Simple({name}){return <main className="wrap"><Card title={name}><p className="muted">Manage your {name.toLowerCase()} with secure account controls and connected REST APIs.</p></Card></main>}
export function AdminPage({name}){const{data}=useQuery({queryKey:['admin'],queryFn:()=>admin.stats().then(r=>r.data)});return <main className="wrap"><Card title={`Admin ${name}`}><pre>{JSON.stringify(data||{},null,2)}</pre></Card></main>}
export function Login(){return <main className="wrap"><Card title="Login"><input className="input" placeholder="Email"/><br/><br/><input className="input" placeholder="Password" type="password"/><br/><br/><button className="btn">Login</button></Card></main>}
export const Register=()=> <Simple name="Register"/>;export const NotFound=()=> <Simple name="404"/>;
